/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Comment = IDL.Rec();
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Feedback = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
Comment.fill(
  IDL.Record({
    'id' : IDL.Nat64,
    'content' : IDL.Text,
    'parentCommentId' : IDL.Opt(IDL.Nat64),
    'children' : IDL.Vec(Comment),
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  })
);
export const DiscussionThread = IDL.Record({
  'id' : IDL.Nat64,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'comments' : IDL.Vec(Comment),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Nat64, IDL.Opt(IDL.Nat64), IDL.Text],
      [IDL.Nat64],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createThread' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat64], []),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllThreads' : IDL.Func([], [IDL.Vec(DiscussionThread)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getThread' : IDL.Func([IDL.Nat64], [IDL.Opt(DiscussionThread)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Comment = IDL.Rec();
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Feedback = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  Comment.fill(
    IDL.Record({
      'id' : IDL.Nat64,
      'content' : IDL.Text,
      'parentCommentId' : IDL.Opt(IDL.Nat64),
      'children' : IDL.Vec(Comment),
      'author' : IDL.Principal,
      'timestamp' : IDL.Int,
    })
  );
  const DiscussionThread = IDL.Record({
    'id' : IDL.Nat64,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'comments' : IDL.Vec(Comment),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Nat64, IDL.Opt(IDL.Nat64), IDL.Text],
        [IDL.Nat64],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createThread' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat64], []),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllThreads' : IDL.Func([], [IDL.Vec(DiscussionThread)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getThread' : IDL.Func([IDL.Nat64], [IDL.Opt(DiscussionThread)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };